### ISSUE TITLE
Update stripes and energy view to use demand.energy and demand.market_value

### ISSUE THREAD

**Issue by simonhac** [opennem/opennem-fe#103]
see `dev` for examples

### energy jsons:
*  https://data.dev.opennem.org.au/v3/stats/au/NEM/energy/all.json
*  https://data.dev.opennem.org.au/v3/stats/au/NEM/VIC1/energy/2022.json

- [x] price chart
- [x] export price chart
- [x] table Av.Value column
- [x] ~~table Contribution to demand to use `demand.energy` (maybe?)~~
- [x] stats table (price)
- [x] 12th month rolling calculation
- [x] interval calculation
- [x] interval filter calculation

### stripe jsons:
* https://data.opennem.org.au/v3/stats/au/{region}/daily.json
* https://data.opennem.org.au/v3/stats/au/all/monthly.json

- [x] vwp
- [x] vwp (inflation adjusted)

**Comment by chienleng** [comment]
@nik I will move this to a FE issue
