### ISSUE TITLE
Add WA data to OpenNEM (would it require a name change OpenN/WEM?!)

### ISSUE THREAD

**Issue by aleith** [opennem/opennem-fe#11]
Apparently the data feed for OpenNEM is from AEMO somewhere in the http://www.nemweb.com.au domain. AEMO plays a different role on the WEM than they do on the NEM so it may be difficult to get this to happen any time soon, but they do make live data for the WEM available here:
http://www.data.wa.aemo.com.au/Electricity/Wholesale-Electricity-Market-WEM/Data 

Name could be OpenNEM+ when it incorporates WA (and then NT)?

**Comment by chienleng** [comment]
WEM on OpenNEM: https://opennem.org.au/energy/wem/?range=7d&interval=30m

**Comment by aleith** [comment]
thanks steven. I'm endeavoring to get a data dump of generation from all assets prior to 2006 from AEMO. I'm not sure what you have prior to 2006, but Simon indicated that some of the data you have needs to be parsed into the correct CSV/JSON to work alongside the existing data 2006-2021.
