### ISSUE TITLE
12 month rolling issues with quarterly, seasonal and half-year grouping

### ISSUE THREAD

**Issue by simonhac** [opennem/opennem-fe#114]
This looks reasonable — Year to August 2022 totals 207,554 GWh:
<img width="500" alt="image" src="https://user-images.githubusercontent.com/20500649/187912157-eaa61662-dc62-4439-b1de-5da32f2feb54.png">

However, this looks dodgy:

1. Year to Winter 2022 totals 620,928 GWh:
<img width="500" alt="image" src="https://user-images.githubusercontent.com/20500649/187912290-d98e31d0-b14b-40c4-a8c0-cf4f8b092edb.png">
  (This should sum the 4 seasons up to and including the selected season, but seems to be summing a period 3 times as long.)

2. Year to 2022Q2 totals 618,004 GWh:
<img width="500" alt="image" src="https://user-images.githubusercontent.com/20500649/187912572-ec3ee5b2-196c-4f8d-9389-dbfafe095b99.png">
  (This should sum the 4 quarters up to and including the selected quarter, but seems to be summing a period 3 times as long.)

3. Year to 2022H1 totals 1,233,554 GWh:
<img width="500" alt="image" src="https://user-images.githubusercontent.com/20500649/187912809-ee09d28b-c8ed-434d-b09c-94f2b72eb92c.png">
  (This should sum the 2 half-years up to and including the selected half-year, but seems to be summing a period 6 times as long)

**Comment by chienleng** [comment]
the base rolling sum is right but I didn't update the period grouping to take into account how the rolling sum works, so it was just summing the rolling sum dataset for season (3 months), quarter (3 months) and half year (6 months).

**Comment by chienleng** [comment]
I should summed up the period first, then run it through the rolling sum calculation.
