### ISSUE TITLE
Permalink to facility page isn't including the header in the route

### ISSUE THREAD

**Issue by nc9** [opennem/opennem-fe#120]
Linking to a facility page, ex.

https://opennem.org.au/facility/au/NEM/TUMUT3/?range=30d&interval=1d

isn't including the top header in the route 

(you can recreate this by just refreshing hard on a facility page). see:

![image](https://user-images.githubusercontent.com/39009487/189825853-afbcd361-4178-46f2-acd8-88dc820ac3e3.png)

**Comment by chienleng** [comment]
there are two Tumut listed: one has `SNOWY2` (has data) and the other has `TUMUT3` (no data).

<img width="1268" alt="Screen Shot 2022-09-13 at 4 46 58 pm" src="https://user-images.githubusercontent.com/349944/189829894-6d39904a-cdc9-4896-9ed9-00c3b6c8dd27.png">
<img width="1262" alt="Screen Shot 2022-09-13 at 4 47 15 pm" src="https://user-images.githubusercontent.com/349944/189829908-358eae1b-369a-4b08-938e-e3967cb89346.png">
