### ISSUE TITLE
Facility chart and table to differentiate source and load power/energy

### ISSUE THREAD

**Issue by chienleng** [opennem/opennem-fe#124]
* Have total reg cap for source and load and add both reg cap lines in power chart. (this should affect the 'Card' component in map view too)
* If there are 'load' units, values should be split up to show both source and load values with updated `Total` label
* Proportion, Cap factor and Av. calculation should take that into account

For example:

https://opennem.org.au/facility/au/NEM/HORNSDPR/?range=3d&interval=30m
| Unit | Registered Cap. | Energy | Proportion | Cap.factor |
| --- | --- | --- | --- | --- |
| HPRG1 — Battery (Discharging) | 150 | 449 | {use source total}% | {use source total}% |
| HPRL1 — Battery (Charging) | 150 | 691 | {use load total}% | {use load total}% |
| Total (Discharging/Charging) | 150/150 | 449/691 | | Av. x%/y% |

https://opennem.org.au/facility/au/NEM/KENNEDY/?range=3d&interval=30m
| Unit | Registered Cap. | Energy | Proportion | Cap.factor |
| --- | --- | --- | --- | --- |
| KEPBG1 — Battery (Discharging) | 2 | 8.8 | {use source total}% | {use source total}% |
| KEPBL1 — Battery (Charging) | 2 | — | {use load total}% | {use load total}% |
| KEPSF1 — Solar (Utility) | 15 | 310 | {use source total}% | {use source total}% |
| KEPWF1 — Wind | 43.2 | 958 | {use source total}% | {use source total}% |
| Total (Discharging, Solar (Utility), Wind/Charging) | 60.2/2 | 1278/— | | Av. x%/y% |

**Comment by simonhac** [comment]
when there’s a load fuel-type and the y-axis is power, please show two registered capacity lines — one for sources above x-axis, and one for loads below the x-axis.
