### ISSUE TITLE
[Compare] feature

### ISSUE THREAD

**Issue by chienleng** [opennem/opennem-fe#131]
* Line chart to compare Metrics between each states (particularly Emission Intensity)
* Maybe re-think how to integrate Stripes using the same Metrics. 

- [x] fix x-axis for year intervals in mobile view
- [x] line dots to have option to render at end of time period rather than beginning
- [x] enhance import/export chart to clearly mark above/below as import/export
- [x] fix temperature 12 mth rolling calculation
- [x] add query params for range/interval selections
- [x] check mobile layout 
- [x] add Compare Regions menu item in mobile drawer
- [x] add feature flag on vol weighted pricing metrics

### Release todos
- [x] remove feature flag 
- [x] create new social media card images for Compare regions
- [x] clean up compare page code (remove stripes related stuff)

**Comment by simonhac** [comment]
@chienleng for v1, perhaps keep stripes different from 'compare' — but using the same metrics.

**Comment by simonhac** [comment]
initial observations:
1. don't show the white part of the 'tooltip pill' if there's no data:
<img width="116" alt="image" src="https://user-images.githubusercontent.com/20500649/214436821-e045ba41-2e02-4a3a-aaf8-ab07be130678.png">

2. for percentages, use format '0.0%' in the tooltip:
<img width="190" alt="image" src="https://user-images.githubusercontent.com/20500649/214436906-36c610b0-25e9-414f-82fa-70ffb8df0823.png">

3. …and in the table:
<img width="375" alt="image" src="https://user-images.githubusercontent.com/20500649/214437045-7aa21c76-736c-4496-be8d-d6e2773792c2.png">

4. in general, don't show a negative portion on the charts:
<img width="328" alt="image" src="https://user-images.githubusercontent.com/20500649/214437262-6571a4be-69b0-425a-a097-4b81af2eb74c.png">

**Comment by simonhac** [comment]
5. add temporal grouping controls — 12 mth rolling, grouping, filtering: 
<img width="454" alt="image" src="https://user-images.githubusercontent.com/20500649/214437649-70ca10b8-ddec-4ab5-a8bc-4a0c8cd22729.png">

**Comment by simonhac** [comment]
6. for temperature series, add `°C` to tooltip and table.
<img width="374" alt="image" src="https://user-images.githubusercontent.com/20500649/214439640-f20336d3-cc9a-46f0-bba9-e8e6f6d21745.png">

**Comment by simonhac** [comment]
7. add series toggle (including shift to deselect others):
<img width="238" alt="image" src="https://user-images.githubusercontent.com/20500649/214439886-0950e487-e309-47bc-8135-80f6a7b2374d.png">

**Comment by simonhac** [comment]
8. add the chart title and units — this is what we have on the energy charts:
<img width="195" alt="image" src="https://user-images.githubusercontent.com/20500649/214457579-daf0b35b-c3d1-4b12-8cc4-d3899eec40e2.png">

(yes, it'll mean that the title of the chart is displayed twice… once on the chart and once in the pop-up menu. is that problematic?)

**Comment by simonhac** [comment]
test comment

**Comment by aleith** [comment]
comparing two graphs, each independently controlled except for time series when the "chained time" icon is checked either within a state or across states or NEM would be neat ! I think i FR it somewhere once.

**Comment by simonhac** [comment]
@chienleng the responsive button-bar changes to mobile/naoor view well before it has to on desktop:

<img width="700" alt="image" src="https://github.com/opennem/opennem-fe/assets/20500649/b473e123-0793-4c3f-a2bd-4bf43f1cb82c">

**Comment by simonhac** [comment]
@chienleng please check that "long-press" to select only a single series on touch device works.

**Comment by simonhac** [comment]
@chienleng please add a new "Minimum temperature" series at the start of this sub-list:
<img width="216" alt="image" src="https://github.com/opennem/opennem-fe/assets/20500649/ebff0222-2f32-4d54-87f6-3bd001fe910d">

**Comment by simonhac** [comment]
@chienleng somewhere along the way we lost the emissions intensity… please bring it back:
<img width="300" alt="image" src="https://github.com/opennem/opennem-fe/assets/20500649/8b8ff8b9-f9ae-4c75-95da-12b9bd8ff4fb">

**Comment by simonhac** [comment]
@chienleng let's:
• change "Net interconnector flow (of demand)" to "Net imports (of demand)"
• move to insider `Proportion` section 
<img width="250" alt="image" src="https://github.com/opennem/opennem-fe/assets/20500649/0be53088-8baa-4736-a003-73104b351344">

**Comment by simonhac** [comment]
@chienleng when there's only one series selected, the tooltip value doesn't show:
<img width="250" alt="image" src="https://github.com/opennem/opennem-fe/assets/20500649/90151028-a054-46c5-9da1-0f81c370a754">

**Comment by simonhac** [comment]
@chienleng Import/Export labels can move out of view when series selection changes. `Imports` 'missing' below:
<img width="300" alt="image" src="https://github.com/opennem/opennem-fe/assets/20500649/11f08762-7345-4409-8181-7c3c5b81b85c">

**Comment by simonhac** [comment]
@chienleng as discussed, please change this into a button:

<img width="180" alt="image" src="https://github.com/opennem/opennem-fe/assets/20500649/0d3403c5-e366-4565-8431-9ff61c4257c4">

**Comment by simonhac** [comment]
@chienleng show the units in the tooltip for the compare view… as we do elsewhere.

compare view:
<img width="400" alt="image" src="https://github.com/opennem/opennem-fe/assets/20500649/1136e846-4408-4188-a64e-2d3a09c49f5e">

energy view:
<img width="450" alt="image" src="https://github.com/opennem/opennem-fe/assets/20500649/b06054ee-c051-4f46-8512-188f9815a640">

**Comment by simonhac** [comment]
@chienleng this is looking good… aiming for consistency here, please change:

* `Net imports` → `Net import proportion`
* `Average value` → `Average spot market value`

<img width="250" alt="image" src="https://github.com/opennem/opennem-fe/assets/20500649/eeaa6ebf-5667-46f0-83b7-dc1449efd202">

**Comment by simonhac** [comment]
@chienleng the 12 Mth Rolling button is very ‘laggy’. when i open the console there’s a hell of a lot of processing that happens and about a 1000ms delay. feels sluggish.

**Comment by simonhac** [comment]
@chienleng tweak stripes menu (left) to be identical to compare menu (right):

<img width="280" alt="image" src="https://github.com/opennem/opennem-fe/assets/20500649/67fc4027-8ea2-4fed-9544-fd4ebb3fc088">
<img width="273" alt="image" src="https://github.com/opennem/opennem-fe/assets/20500649/9a12802a-09b8-41c4-a9ab-5a4797c9e889">

**Comment by chienleng** [comment]
Deployed to production.
https://opennem.org.au/compare/?range=all-12-mth-rolling&interval=1M&metric=renewablesProportion
