### ISSUE TITLE
Add CC-BY to website footer

### ISSUE THREAD

**Issue by gmmspi** [opennem/opennem-fe#181]
Add CC-BY to website footer and potentially outputs of the export tool

**Comment by chienleng** [comment]
<img width="380" alt="Screenshot 2023-06-08 at 12 17 26 pm" src="https://github.com/opennem/opennem-fe/assets/349944/0d465142-785c-47bc-a23b-0292b793f956">
<img width="393" alt="Screenshot 2023-06-08 at 12 17 14 pm" src="https://github.com/opennem/opennem-fe/assets/349944/cb8faf7b-2061-49ee-a217-f808cc2cefb2">

added to footer and about page. it's linked to: https://creativecommons.org/licenses/by/4.0/

**Comment by chienleng** [comment]
netlify preview: https://64813feb6204ab1136d12c1a--cute-tiramisu-1ce85b.netlify.app/energy/nem/?range=7d&interval=30m

**Comment by gmmspi** [comment]
This is great @chienleng 

How hard would it be to also apply similar to exported charts? Say, in the bottom right of the export?


![Image](https://github.com/opennem/opennem-fe/assets/126639348/03a31737-63a6-4afe-b623-b86d15762d37)

**Comment by chienleng** [comment]
Easy to add. Since it's exported and not interactive, should I just use the CC-BY logo or spelt out the license `Licence: CC BY 4.0`.

**Comment by gmmspi** [comment]
I think the logo would be good

**Comment by chienleng** [comment]
![20230509 OpenNEM](https://github.com/opennem/opennem-fe/assets/349944/bae407a9-6b51-4c61-b7fc-47fcb598fd25)
<img width="683" alt="Screenshot 2023-06-09 at 3 18 29 pm" src="https://github.com/opennem/opennem-fe/assets/349944/cf42fbfd-1e3d-4811-a3f4-e721eaf4155e">
