### ISSUE TITLE
Remove area under 0% when showing line/percentage.

### ISSUE THREAD

**Issue by simonhac** [opennem/opennem-fe#187]
<img width="400" alt="image" src="https://github.com/opennem/opennem-fe/assets/20500649/dc7f8eaf-05a6-45b8-be5a-fc1ab8a77497">

**Comment by chienleng** [comment]
Fixed. `v4.17.1`
<img width="1018" alt="Screenshot 2023-07-25 at 10 28 06 am" src="https://github.com/opennem/opennem-fe/assets/349944/dbf4067e-5ad1-4168-80b2-c6e92439ef28">
