### ISSUE TITLE
Bad x-axis label spacing on line charts on mobile

### ISSUE THREAD

**Issue by simonhac** [opennem/opennem-fe#188]
<img width="300" alt="image" src="https://github.com/opennem/opennem-fe/assets/20500649/ffad9364-2fc8-4bd2-9ffd-41e88a549774">

**Comment by aleith** [comment]
obviously needs to drop some of the year labels from appearing but this is where i like to use text on the 45° to vertical too.

**Comment by chienleng** [comment]
![Image](https://github.com/opennem/opennem-fe/assets/349944/7ca298be-fec3-44dc-ad66-9a0d229016a2)

fixed.
