### ISSUE TITLE
Enable text compression

### ISSUE THREAD

**Issue by rowanstenhouse** [opennem/opennem-fe#19]
Hi team,

Love your work! OpenNEM is a great app. Just noticed what is hopefully a quick fix, enabling gzip compression on your text assets.

From what I can tell the app is serving JS/CSS assets from Cloudfront/S3. You can set the CF distribution to compress objects automatically https://aws.amazon.com/blogs/aws/new-gzip-compression-support-for-amazon-cloudfront/

Should help to serve up the site quicker plus save you on CDN costs

**Comment by chienleng** [comment]
enabled compression: `content-encoding: br`
