### ISSUE TITLE
In power series emissions only being shown on 5m view not on 30m view

### ISSUE THREAD

**Issue by nc9** [opennem/opennem-fe#191]
https://dev.opennem.org.au/energy/nsw1/?range=7d&interval=5m

5m view for NSW shows emissions in the power series correctly:

![image](https://github.com/opennem/opennem-fe/assets/39009487/85bb6f74-582e-4bce-b7f4-0480adefe76f)

empty on 30m view - assume this is around how the frontend aggregation works

![image](https://github.com/opennem/opennem-fe/assets/39009487/d32b7142-08d9-44a1-85cb-6f57bf72176d)

**Comment by simonhac** [comment]
@chienleng i don't know how to mark this as top priority… but please treat it as such.

**Comment by nc9** [comment]
i'll import the backend labels into this project as well for priorities - make the board more consistent

**Comment by chienleng** [comment]
Power view with emissions update: https://feature-191-in-power-series.opennem-fe-bl7.pages.dev/energy/nem/?range=7d&interval=30m

* note this preview site is calling [data.dev](http://data.dev/). and the data is bit funky atm. see solar chart
* 30m emissions vol added to 'rollup' function
* added a workaround to divide the emissions data by 12 for NEM regions and by 2 for All and WEM regions (the history.data still needs to be updated)
* fix issue with EI calculations in power data view
* I've noticed a new emissions_factor, should i use this to calculate intensity?

**Comment by chienleng** [comment]
30m view is now working on preview site.
