### ISSUE TITLE
Request: Toggle source

### ISSUE THREAD

**Issue by jamesdeluk** [opennem/opennem-fe#2]
Is it possible to implement a function so I can toggle a source on/off from the chart and table? So, for example, I can see the correlation between all the non-coal sources.

Thanks!

**Comment by aleith** [comment]
or alternatively to group a set of generation sources into Fossil Fuels | Renewables | Dispatchable | Non-Dispatchable

**Comment by chienleng** [comment]
A basic implementation of the toggle is now live. 

<img width="1281" alt="series-toggle" src="https://user-images.githubusercontent.com/349944/47545921-88211480-d93a-11e8-886b-42ada47ca4db.png">
