### ISSUE TITLE
Time-of-day plots

### ISSUE THREAD

**Issue by simonhac** [opennem/opennem-fe#203]
I think these charts (from [gridstatus.io](https://www.gridstatus.io/live/caiso)) give great insight into key characteristics of our power system:

<img width="300" alt="image" src="https://github.com/opennem/opennem-fe/assets/20500649/5d0f3598-a219-41cd-99b6-302b21d4fb22">
<img width="250" alt="image" src="https://github.com/opennem/opennem-fe/assets/20500649/94305bc1-4f6c-468d-b921-467c8ec59674">

<img width="300" alt="image" src="https://github.com/opennem/opennem-fe/assets/20500649/f42d95b5-744e-4bad-be0e-24b43485a38a">
<img width="300" alt="image" src="https://github.com/opennem/opennem-fe/assets/20500649/0cf63142-38e9-4654-8a55-3016f656469c">

We already have the data to show last 7 days… easy to extend to last 30.

Tasks:

- [x] support 28D (wait for 30d.json)
- [x] responsive update
- [x] date axis formatting
- [x] view switcher
- [x] show unit
- [x] invert load values
- [x] fix issue with grouping calculations not taking nulls into account
- [x] Net line (similar to Renewables line)
- [x] highlight or thicken line when hovering over table row
- [x] add query string support 
- [x] centre dot
- [x] add Net and Renewables charts
- [x] add Price chart
- [x] add Temperature chart
- [x] update Toggle design
- [x] add Average stacked
- [x] show average value over all periods (all shown days) when there’s no focus
- [ ] (consider) adding chart resizing functionality
- [x] date brush zoom
- [x] remove link from button and table row
- [ ] Emission Intensity chart
- [x] click on unit to change multiplier (SI prefix)

**Comment by simonhac** [comment]
Ideally would like to be able to chart any (and possibly multiple) of the series from this table (in its various forms):

<img width="250" alt="image" src="https://github.com/opennem/opennem-fe/assets/20500649/29a14a7e-8e16-4d14-a4f4-8395a88f826d">

**Comment by aleith** [comment]
i made an animation of solar PV for each hour period in the day over the years showing `annual average`, `annual minimum` and `annual maximum`. these three are all pretty useful in terms of grid management issues like peak demand minimum and maximum  events.

**Comment by simonhac** [comment]
@chienleng please remember to add a new (toggleable) series for `Net`.

**Comment by simonhac** [comment]
can we also please add temperature 🙏

**Comment by simonhac** [comment]
…and also please add price 🙏

**Comment by simonhac** [comment]
…and also add emissions intensity (if `Emissions Charts` feature enabled) 🙏

**Comment by simonhac** [comment]
(i added "click on unit to change multiplier (SI prefix)")

**Comment by aleith** [comment]
I could ask [Dean Sharafi](https://www.linkedin.com/in/dean-sharafi-5524b7b4/) who is GM of systems at AEMO WA on behalf of openNEM if you want me too. he's been really helpful in answering questions in the past. 

I previously had concerns about new hybrid facilities where wind farms were to add PV and/or batteries and dispatch under a single facility code. Not sure the ever got answered, I think the SCADA data distinguishes between what happens behind the meter at generation facilities but cant be sure now, was a long time ago.
