### ISSUE TITLE
Allow resizing of chart width and height 

### ISSUE THREAD

**Issue by simonhac** [opennem/opennem-fe#204]
Problem: Often a chart (especially emissions intensity and price) has proportions that makes it hard to see the variation, obscuring an important observation.

Proposed solution: Add controls/handles to allow user to easily change the width and height of each chart.

Something like this. Only show when pointer is in the vicinity.

<img width="600" alt="image" src="https://github.com/opennem/opennem-fe/assets/20500649/2d7138de-487e-4e28-ac8a-b538aac39313">

**Comment by chienleng** [comment]
- [x] disable resize for touch device
- [ ] increase chart heights (~+50%) in mobile view (especially for Intensity and Price)
- [ ] adjust price log chart heights as well

**Comment by simonhac** [comment]
looking really good.

> increase chart heights (~+50%) in mobile view (especially for Intensity and Price)

i don't think we need to do it for the power/energy and emissions charts… but useful for intensity, price and probably temperature.
