### ISSUE TITLE
Option to show/hide x-axis labels on charts

### ISSUE THREAD

**Issue by simonhac** [opennem/opennem-fe#205]
Problem: When screenshotting charts for sharing on social media, most of the charts don't have an x-axis.

Solution: Give user the option of hiding/showing x-axis on any chart. Perhaps a simple button to hide/show the x-axis?

<img width="500" alt="image" src="https://github.com/opennem/opennem-fe/assets/20500649/0c9524d6-fc13-46ee-a7fa-f39bc57d84dc">

**Comment by aleith** [comment]
IMHO it's a sin of infographics to not label graphs when sharing with others/public. it should be non-negotiable or at least default to on.

**Comment by chienleng** [comment]
`v4.18.0` - date axis visible for all charts
