### ISSUE TITLE
Display of $0 prices

### ISSUE THREAD

**Issue by jakeanq** [opennem/opennem-fe#26]
If the electricity price is exactly $0.00 (this happened last night near midnight for SA), the data will not display on the graph or in the summary table and instead looks like missing data.

![image](https://user-images.githubusercontent.com/3282717/73603312-bb882f80-45d0-11ea-9b69-87e7909b2b82.png)

**Comment by chienleng** [comment]
Fixed.

<img width="1015" alt="Screen Shot 2020-02-02 at 4 38 27 pm" src="https://user-images.githubusercontent.com/349944/73603804-761d2f80-45db-11ea-9a4e-a1bb09cfcf26.png">
