### ISSUE TITLE
Vertical Axis labels overlaid on data. 

### ISSUE THREAD

**Issue by aleith** [opennem/opennem-fe#29]
It's usually considered good design to have axis labels in white space to make them more legible. While overlaying them on the data plot saves space, the grey colour and minor amount of drop-shadow effect on the digit glyphs makes them pretty illegible when plotted over coal (brown and charcoal coloured) and pumps (dark purple).

Recommend either more drop-shadow, context sensitive text colour or put them to the left hand side of data. The later would allow more easy editing of text sizes/legibility in post-production of graphs in vector and pixel editing software.

**Comment by chienleng** [comment]
Agree. I've been trying to figure out the best way to place them (there is also a right y-axis). Placing them outside of the plot area will be the best.

**Comment by aleith** [comment]
it's trade off between economy with screen realestate and legibility I suppose. I err towards legibility and post-production, but I'm going to always say that as a designer. Many users, especially on mobile devices may disagree :-)
