### ISSUE TITLE
Yay WA is now included! WA generation and consumption data lacking rooftop PV

### ISSUE THREAD

**Issue by aleith** [opennem/opennem-fe#30]
I wonder if the postcode PV sources used for estimating RooftopPV on the NEM are applicable to WA? WA has some of the highest penetrations of rooftop PV (residential, commercial and now industrial is accelerating quickly) in Australia and it would make more sense of the hard ramping on coal units to see the rooftopPV flooding into the daytime market.

**Comment by simonhac** [comment]
definitely something we're looking at — very much in active development.

we currently use AEMO's ASEFS data feed, but they do not have a public equivalent for WA.

APVI has an estimate for WA, but last time we checked, their NEM estimates differed significantly from AEMOs.

watch this space.

**Comment by aleith** [comment]
I asked the head of AEMO in WA about this some time ago when I was looking to fork OpenNEM to show WA data and other things. He put me in touch with someone there, I can't find the email thread ATM. The short answer was the data is in a different format and they have no plans to harmonise it with ENM data format, but I don't see why it would be that hard to write a little shim code to convert it to the same data format that is used on NEM and which OpenNEM accesses ATM. 

Happy to connect you with the relevant people at WA AEMO office if that helps. SEN has a good relationship with them.

**Comment by simonhac** [comment]
yes, please make the connection. 

we will write an adaptor for any format.

**Comment by aleith** [comment]
just before i contact AEMO again, can I ask where you are getting the existing Live and historical data from for WA generation and demand? AEMO or SCADA?

**Comment by simonhac** [comment]
- https://aemo.com.au/aemo/data/wa/infographic/generation.csv
- http://data.wa.aemo.com.au/public/public-data/datafiles/facility-scada/facility-scada-{year}-{month}.csv
- http://data.wa.aemo.com.au/datafiles/facility-scada/

**Comment by aleith** [comment]
ta, in browser I get a 404 on the second one, does it need authenticated access?

**Comment by simonhac** [comment]
that URL includes `{year}` and `{month}` variable substitutions — i grabbed it directly from the code.

at runtime actual values are substituted in eg:
   http://data.wa.aemo.com.au/public/public-data/datafiles/facility-scada/facility-scada-2019-10.csv

**Comment by aleith** [comment]
Thx again. one more thing does the public facing opennem.org.au include an approximation of behind the meter consumption, or is RooftopPV showing an approximation of purely exports from behind the meters. i.e. of RooftopPV and possibly BTM batteries?

**Comment by simonhac** [comment]
we use AEMO's [ASEFS](https://aemo.com.au/energy-systems/electricity/national-electricity-market-nem/nem-forecasting-and-planning/operational-forecasting/solar-and-wind-energy-forecasting/australian-solar-energy-forecasting-system) data. the ASEFS estimates all behind-the-meter solar generation, which is the same as self-consumption plus export.

(nb. we are also talking with AEMO, albeit east coast.)

**Comment by aleith** [comment]
great thx. I put you in touch with them as soon as i get a reply.

**Comment by aleith** [comment]
thanks and well done to those who licensed and wrangled the PV data !!
