### ISSUE TITLE
Prices not accurately reflected on openNEM

### ISSUE THREAD

**Issue by AshTex** [opennem/opennem-fe#38]
The following price spikes:
![image](https://user-images.githubusercontent.com/11602677/99471663-25749880-299b-11eb-85df-e9a83ce74a37.png)

Where not reflected in openNEM data (NSW example, but seems to be true for all the price spikes):
![image](https://user-images.githubusercontent.com/11602677/99471795-6a98ca80-299b-11eb-8d38-64d131a97fa7.png)

**Comment by dylanjmcconnell** [comment]
openNEM uses the Trading Interval (30minute), on which settlement is based. The table you've copied above shows the Dispatch Interval (5 minute) prices.

**Comment by AshTex** [comment]
Ok so if I understand correctly openNEM's 5m price data is a rolling average of the last 6 Dispatch Interval prices?

**Comment by dylanjmcconnell** [comment]
No - it's directly from the 30 minute trading interval datasets, published by AEMO (we don't do any averaging of dispatch prices). Specifcially, from the `TRADINGPRICE` table in the MMS.  

The trading price published by AEMO is generally the average of the five-minute prices within a 30-minute dispatch interval (not a rolling average).

**Comment by AshTex** [comment]
Cheers for the explanation. 

Is there any appetite reflect the 5 minute trading price along with the 5 minute generation data?

**Comment by simonhac** [comment]
we'll definitely be adopting 5 minute trading price when 5 minute settlement comes in on 1 October 2021.

i don't feel there's a strong case for allowing 30 minute and hypothetical 5 minute before then. but if you feel otherwise, please make a case.
