### ISSUE TITLE
For "Season", "Half Year" & "Fin Year" views, the selected period data table fails to populate.

### ISSUE THREAD

**Issue by aleith** [opennem/opennem-fe#43]
Tested on macOS Safari, iPhone Safari and Chrome. 

Steps to reproduce:
1. Select NEM or any state and "Energy" from top menus.
2. Select "ALL" from the {1D, 3D, 7D, 30D, 1Y, ALL} duration radio buttons.
3. Select "Quarter", "Month" or "year" and click on a column in either of the graphs and the data summary gets populated with the energy and percentages for that period.
4. Select "Season", "Half Year" & "Fin Year" and click on a column in either of the graphs and the data summary shows no data for energy nor percentages for that period.

**Comment by chienleng** [comment]
Should be fixed.
