### ISSUE TITLE
WA consistently shows overnight PV output for 1-2% of generation. 

### ISSUE THREAD

**Issue by aleith** [opennem/opennem-fe#59]
<img width="1152" alt="Screen Shot 2021-11-09 at 11 08 27 pm" src="https://user-images.githubusercontent.com/1528794/140922135-78ff977a-729c-4dc9-b452-fb15130140e8.png"
<img width="1821" alt="Screen Shot 2021-11-09 at 11 13 07 pm" src="https://user-images.githubusercontent.com/1528794/140922369-ed1f99a7-6503-48e9-af4b-e33633148854.png">
>
Must be some kind of calculation error for both utility and rooftop PV (different data sources for one)… any idea why this is happening for WA … and now I look into it, in other states also. Is this a known issue I can report back to people on NEM Watch who use opennem regularly?
<img width="1856" alt="Screen Shot 2021-11-09 at 11 15 34 pm" src="https://user-images.githubusercontent.com/1528794/140923323-a8c2740c-254a-4a17-83a5-52d6e470d405.png">

This is crazy, and it's not a function of the browser code, adding back the other generation Solar still is visible overnight.

**Comment by aleith** [comment]
all the other NEM states like NSW showing rooftop solar generation at night from about midnight till down and ramping up as it goes!

**Comment by chienleng** [comment]
it could be because how OpenNEM interpolates the rooftop solar data. Could be partly data and FE issue. Will take a deeper look in the next few days.

**Comment by aleith** [comment]
thanks Steven

**Comment by chienleng** [comment]
I believe the data has been fixed.

<img width="812" alt="Screen Shot 2022-07-29 at 2 33 55 pm" src="https://user-images.githubusercontent.com/349944/181683482-530adeb7-9708-472c-961f-a3d54e917df6.png">
