### ISSUE TITLE
minor bug - twitter card thumbnail using development url

### ISSUE THREAD

**Issue by charliedotau** [opennem/opennem-fe#6]
Hi there,

I've just noticed a minor bug.     If you look at the Twitter Card metadata on the production site, you'll notice the `twitter:image:src` points to a URL of an image.   However the URL of the image is pointing to the development subdomain, rather than the live site. Needless to say, nothing on the production site should reference the development site.

See attached.
![screen shot 2019-01-13 at 10 18 52 am](https://user-images.githubusercontent.com/9892745/51079557-28f2c500-171d-11e9-8cf7-9b0cc714f546.png)

**Comment by chienleng** [comment]
This one should be fixed.
