### ISSUE TITLE
"Up" and "Down" arrows not working as they're supposed to in Facility view

### ISSUE THREAD

**Issue by aleith** [opennem/opennem-fe#93]
in the detailed Facility view under the Facilities set of views, there's up and down arrows in circles on the top right corner of the page. 
<img width="563" alt="Screen Shot 2022-06-29 at 2 16 31 pm" src="https://user-images.githubusercontent.com/1528794/176350554-c31136f9-2a45-4382-9a61-c67eb716acc0.png">

They should advance or regress through the previously filtered list of facilities on the main facilities page, but clicking on either of them just redirects the browser to the homepage showing Energy on the NEM, the default view.

It would be a handy feature to get working.

tested in Safari, Firefox and Chrome for macOS Big Sur 11.6.7

**Comment by chienleng** [comment]
also need to check the Back to Facilities button
